trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl https://api.nest.saker.build/bundle/download/saker.build-v$(curl -s https://mirror.nest.saker.build/badges/saker.build/latest.txt) -o saker.build.jar
  displayName: 'Download saker.build'
- script: |
    set -e
    curl -s https://gist.githubusercontent.com/Sipkab/f71ecb5e2167a2b0fced6736d703b8a5/raw/azure_ubuntu_jdksetup.sh -o /tmp/azure_ubuntu_jdksetup.sh
    echo "##vso[task.setvariable variable=JAVA_HOME_8_X64]$(bash /tmp/azure_ubuntu_jdksetup.sh 8)" &
    echo "##vso[task.setvariable variable=JAVA_HOME_9_X64]$(bash /tmp/azure_ubuntu_jdksetup.sh 9)" &
    echo "##vso[task.setvariable variable=JAVA_HOME_12_X64]$(bash /tmp/azure_ubuntu_jdksetup.sh 12)" &
    echo "##vso[task.setvariable variable=JAVA_HOME_13_X64]$(bash /tmp/azure_ubuntu_jdksetup.sh 13)" &
    wait < <(jobs -p)
  displayName: 'Setup JDKs'
- script: java -jar saker.build.jar -bd build "-EUsaker.java.jre.install.locations=$(JAVA_HOME_8_X64);$(JAVA_HOME_9_X64);$(JAVA_HOME_12_X64);$(JAVA_HOME_13_X64)" test
  displayName: 'Test'
- script: java -jar saker.build.jar -bd build "-EUsaker.java.jre.install.locations=$(JAVA_HOME_8_X64);$(JAVA_HOME_9_X64);$(JAVA_HOME_12_X64);$(JAVA_HOME_13_X64)" exportall
  displayName: 'Export'
