trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl -s https://api.nest.saker.build/bundle/download/saker.build-v0.8.0 -o saker.build.jar
  displayName: 'Download saker.build'
- script: java -jar saker.build.jar -bd build "-EUsaker.java.jre.install.locations=${JAVA_HOME_8_X64};${JAVA_HOME_9_X64};${JAVA_HOME_12_X64};${JAVA_HOME_13_X64}" test
  displayName: 'Test'  
- script: java -jar saker.build.jar -bd build "-EUsaker.java.jre.install.locations=${JAVA_HOME_8_X64};${JAVA_HOME_9_X64};${JAVA_HOME_12_X64};${JAVA_HOME_13_X64}" exportall
  displayName: 'Export'