trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl -s https://api.nest.saker.build/bundle/download/saker.build-v0.8.0 -o saker.build.jar
  displayName: 'Download saker.build'
- script: |
    set -e
    echo "##vso[task.setvariable variable=JAVA_HOME_8_X64]$(bash azure_jdksetup.sh 8)" &
    echo "##vso[task.setvariable variable=JAVA_HOME_9_X64]$(bash azure_jdksetup.sh 9)" &
    echo "##vso[task.setvariable variable=JAVA_HOME_12_X64]$(bash azure_jdksetup.sh 12)" &
    echo "##vso[task.setvariable variable=JAVA_HOME_13_X64]$(bash azure_jdksetup.sh 13)" &
    wait < <(jobs -p)
  displayName: 'Setup JDKs'
- script: java -jar saker.build.jar -bd build "-EUsaker.java.jre.install.locations=$(JAVA_HOME_8_X64);$(JAVA_HOME_9_X64);$(JAVA_HOME_12_X64);$(JAVA_HOME_13_X64)" test
  displayName: 'Test'
- script: java -jar saker.build.jar -bd build "-EUsaker.java.jre.install.locations=$(JAVA_HOME_8_X64);$(JAVA_HOME_9_X64);$(JAVA_HOME_12_X64);$(JAVA_HOME_13_X64)" exportall
  displayName: 'Export'
