package saker.java.compiler.impl.compile;

public enum CompileFileTags {
	INPUT_SOURCE,
	INPUT_CLASSPATH,
	INPUT_MODULEPATH,
	INPUT_BOOT_CLASSPATH,

	OUTPUT_CLASS,
	OUTPUT_GENERATED_CLASS,
	OUTPUT_GENERATED_SOURCE,
	OUTPUT_GENERATED_RESOURCE,

	;
}